setting:
 debug: true #输出调试信息
 playerJoinMessageEnable: true #玩家加入游戏是否显示提示信息
 playerJoinMessage: 
  - '§c============================'
  - '§a本服已启用消费飞行插件，欢迎使用！！！'
  - '§c============================'
 level:
  enable: true #是否启用等级消费
  message: '服务器尚未启用消费等级进行飞行！'  #在未启用等级消费的时候，玩家输入了用等级飞行的命令而显示的提示信息
  time: 120 #启用等级消费，消耗1级可飞行的时间-秒
 vault:
  enable: true #是否启用金钱消费，需要Vault前置
  message: '服务器尚未启用消费金币进行飞行！'  #在未启用金币消费的时候，玩家输入了用金币飞行的命令而显示的提示信息
  time: 120 #1游戏币可飞行的时间-秒